### ISSUE TITLE
plugin does not create it's own bot user

### ISSUE THREAD

**Issue by jdbarnes-isi** [cpanato/mattermost-plugin-alertmanager#10]
Zoom, GitHub, GitLab, etc plugins all create their own bot user for integration.

I will create a new bot user for alertmanager, but it should not be necessary if this is normal in the plugin universe.

**Comment by cpanato** [comment]
thanks and sorry for the long delay to reply, yes we can create the bot, are you willing to open a PR for that?

**Comment by bbodenmiller** [comment]
@cpanato any updates on this? Here's an example: https://docs.mattermost.com/developer/bot-accounts.html#id2

**Comment by cpanato** [comment]
@bbodenmiller I used to work for Mattermost 😄 this plugin was created before the bot concept exists.

Are you willing to implement that and open a PR?

**Comment by cpanato** [comment]
the plugin create the bot user now 

https://github.com/cpanato/mattermost-plugin-alertmanager/releases/tag/v0.1.0

/close
