### ISSUE TITLE
Expiring a silence is a bit unclear as the configuration number is not obvious.

### ISSUE THREAD

**Issue by DHaussermann** [cpanato/mattermost-plugin-alertmanager#115]
When running the slash command to expire a silence - providing the "configuration Number" is confusing at first because we don't use that term on the admin UI side and users may think the value come from AlertsManager. 

Also it's confusing that the record set starts at ID `0`.  Developers tend to start counting at 0 but when a record set is shown in a UI it should start at `1`.

We should add the "Configuration Number" label in the Admin UI to make this more obvious and start counting records at 1.

**Comment by cpanato** [comment]
did some updates, but the configuration number starts at 0 and not at 1

**Comment by cpanato** [comment]
closing
