### ISSUE TITLE
Initial webhook event when an alert starts is not being delivered

### ISSUE THREAD

**Issue by DHaussermann** [cpanato/mattermost-plugin-alertmanager#117]
I'm seeing an issue where I can run the `alerts` command and see all my alerts correctly. However I don't get the initial webhook event when an alert first occurs. 

Steps:
- Setup and configure AletsManager plugin
![image](https://user-images.githubusercontent.com/35588783/216707496-86f762b9-927e-4db0-a414-52805cdebbf3.png)
- Supply the webhook and token in `alertmanager.yml`
```
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: '<my-url>/plugins/alertmanager/api/webhook?token=<my-token>'
      ```  
- Trigger an alert in Prometheus
- Watch the Alert apper in the AlertManager UI
- Return to the Mattermost channel
**Observed**: 
A. No webhook event was posted when the alert started
B. Running  the Alert command shows the new alert listed

**Comment by DHaussermann** [comment]
@hanzei are you able to help me narrow this down? The config should be correct as I can see all the data when I initiate the request from Mattermost.  

Does the webhook event delivery not use the same config and token as requests going to AlertManager? 
The description on the token field reads "_The token used to configure the webhook for AlertManager. The token is validates for each webhook request by the Mattermost server._"

**Comment by hanzei** [comment]
@DHaussermann To double check: What URL did you use for the webhook? Can you share a screenshot of the UI used to configure it?

**Comment by DHaussermann** [comment]
@hanzei yes, to be more specific, the URL line looks like this:
`  - url: 'https://dkh-7-7-pre-package-2.test.mattermost.cloud/plugins/alertmanager/api/webhook?token=<my-token>'`

I also notice now there is more info in the AlertManager console...
```
ts=2023-02-05T03:35:32.024Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="web.hook/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://dkh-7-7-pre-package-2.test.mattermost.cloud/plugins/alertmanager/api/webhook?token=<my-token>: Invalid or missing token\n"
``` 
Seems the AlertManger is certainly trying to send the initial event. Is there a way to confirm (maybe with curl or postman) that the server is exposing the webhook endpoint?

**Comment by hanzei** [comment]
Good catch @DHaussermann. This is indeed a bug. Submitted https://github.com/cpanato/mattermost-plugin-alertmanager/pull/118 to fix it.

**Comment by DHaussermann** [comment]
Tested and passed.
- I see the initial webhook firing as expected now
- I applied the code change to the same server with sam number of silences to ensure I was retesting the same scenario
- The 400 error did not ocur un the console after seeing the webhook fire several times. 
- No issues found 

LGTM!  Thanks @hanzei 🎉

**Comment by tgy** [comment]
@DHaussermann @cpanato is it possible to generate a new release with this fix please? :angel:

**Comment by DHaussermann** [comment]
Hi @tgy,
I'm fairly creation that we pulled this fix across to the Mattermost repo and so we included it before packaging the `0.4.0` release that is available here https://github.com/mattermost/mattermost-plugin-alertmanager/releases/tag/v0.4.0

**Comment by tgy** [comment]
@DHaussermann how is that possible? the fix was merged in february but the `0.4.0` version was released beginning of january. maybe there's something i don't understand about the temporality of these releases?

**Comment by DHaussermann** [comment]
Hi @tgy, 
The issue was pulled across to the Mattermost repo on Feb 6 here https://github.com/mattermost/mattermost-plugin-alertmanager/commit/cf25a9e4c32b6d6cc2d1d9e7582a1e9b1f31ce89 and then the release from the Mattermost org was cut the same day. The release in the other repo is actually from February. 

It's a bit confusing because we solved 2 issues but those have not yet been released from this repo yet. 
The normal process is to cut a release here first which didn't happen and unfortunately makes it unclear that the other release has a code change added.

**Comment by tgy** [comment]
@DHaussermann thanks. I don't have access to the links you are sharing. Are they private repositories? I installed the release from this repo (the one this issue is attached to).

**Comment by jangrewe** [comment]
@cpanato There is no Alertmanager Plugin on the Marketplace, or rather: the page links here.

I've recently upgraded to 0.4.0, removed all config, set it up again from scratch, updated the URL and token in Alertmanager, but:
```
ts=2023-10-07T00:36:15.769Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=11 err="default/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://mattermost.<redacted>.tld/plugins/alertmanager/api/webhook?token=<redacted>: Invalid or missing token\n"
```

**Comment by cpanato** [comment]
@jangrewe thanks for the report, I will try to reproduce the issue. What is the mattermost version that you are using?

**Comment by jangrewe** [comment]
Thank you! I'm using 9.0.1-rc1.

**Comment by cpanato** [comment]
> Thank you! I'm using 9.1.0-rc2.

ok, i was able to reproduce, looks like the new release of mattermost have some things we need to update to make the plugin work again

**Comment by cpanato** [comment]
@jangrewe looks like it is in the token :/ if the token have a `_` it is not being sent or something happens

so to fix that you need to set in the alertmanager config the double quotes and single quotes in the token, like

```
...
receivers:
- name: 'mattermost-alertmananger'
  webhook_configs:
  - send_resolved: true
    url: "https://xoxoxoxox/plugins/alertmanager/api/webhook?token='4GKPhZpAx13WxlvLz-nH0dFnn26F5Z6z'"
```

that fixed the issue

**Comment by jangrewe** [comment]
Thanks, using the quoting pattern you propose works for me, too! :-)

**Comment by cmuench** [comment]
This fixed also my problem. Would be nice to add an example to the README.md file.

**Comment by cpanato** [comment]
fixed here https://github.com/cpanato/mattermost-plugin-alertmanager/pull/360
