### ISSUE TITLE
Working with multiple teams?

### ISSUE THREAD

**Issue by jdbarnes-isi** [cpanato/mattermost-plugin-alertmanager#12]
Hi, I am running a server with 2 teams, 1 for a web portal and 1 for a remote site. I was trying to figure out if it's possible to send alerts to both teams, but the configuration for this plugin seems to point to only alerting a single team. 

Is there a way to send alerts 2 different teams on the same mattermost instance using different receivers or something?

**Comment by cpanato** [comment]
hum, We can add a config to send the alert to multiple teams. Is it something you want to try out?

**Comment by jdbarnes-isi** [comment]
I have 2 separate teams, so it would be nice to send to different ones for different alerts/alertmanagers etc. Right now I have 2 alertmanagers sending to 1 team when it should be sending to 2. I haven't really checked back on implementing code changes for a while, been busy with other operational things.

Thanks for pinging on these.

**Comment by cpanato** [comment]
@jdbarnes-isi I will think about how to do that.

**Comment by slidingshade** [comment]
We also have alertmanagers from different clusters, so it would be great to receive notifcations to different channels from several alertmanagers

**Comment by maxgorovenko** [comment]
Our team made a solution, check this https://github.com/cpanato/mattermost-plugin-alertmanager/pull/48

**Comment by cpanato** [comment]
this is done! thanks
release come next
