### ISSUE TITLE
Create 0.0.2 release

### ISSUE THREAD

**Issue by securitykernel** [cpanato/mattermost-plugin-alertmanager#13]
Would you mind creating a new release, at least for the fix in f46313dedb1ba4bdf5fec935f93bfe56666a38a7?

**Comment by cpanato** [comment]
will make some change and then release it

**Comment by cpanato** [comment]
done 
https://github.com/cpanato/mattermost-plugin-alertmanager/releases/tag/v0.1.0

/close
