### ISSUE TITLE
Failed to start plugin 0.1.0

### ISSUE THREAD

**Issue by edwelch** [cpanato/mattermost-plugin-alertmanager#17]
Server Version: **5.26.2**
Plugin Version: **0.1.0**
Failed to start. Here some logs:

`{"level":"error","ts":1617279277.5100725,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"SqlTeamStore.GetByName: Не удалось найти существующую команду., name=http://mt.lan:8065/team-dev,sql: no rows in result set"}
{"level":"info","ts":1617279277.5121043,"caller":"bleveengine/bleve.go:267","msg":"UpdateConf Bleve"}
{"level":"warn","ts":1617279277.5422955,"caller":"plugin/hclog_adapter.go:69","msg":"error closing client during Kill","plugin_id":"com.cpanato.alertmanager","wrapped_extras":"errunexpected EOF"}
{"level":"warn","ts":1617279277.5427206,"caller":"plugin/hclog_adapter.go:71","msg":"plugin failed to exit gracefully","plugin_id":"com.cpanato.alertmanager"}
{"level":"error","ts":1617279277.5431993,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"SqlTeamStore.GetByName: Не удалось найти существующую команду., name=http://mt.lan:8065/team-dev,sql: no rows in result set"}
{"level":"error","ts":1617279277.603872,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"SqlTeamStore.GetByName: Не удалось найти существующую команду., name=http://mt.lan:8065/team-dev,sql: no rows in result set"}
{"level":"info","ts":1617279277.6219296,"caller":"bleveengine/bleve.go:267","msg":"UpdateConf Bleve"}
{"level":"error","ts":1617279277.6514676,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"SqlTeamStore.GetByName: Не удалось найти существующую команду., name=http://mt.lan:8065/team-dev,sql: no rows in result set"}`

**Comment by cpanato** [comment]
there are some logs that I cannot read because it is in another language.

Did you configure the settings?

**Comment by edwelch** [comment]
@cpanato here corrected log file:

`
{"level":"error","ts":1617279277.5100725,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"SqlTeamStore.GetByName: Couldn't find an existing command., name=http://mt.lan:8065/team-dev,sql: no rows in result set"} {"level":"info","ts":1617279277.5121043,"caller":"bleveengine/bleve.go:267","msg":"UpdateConf Bleve"} {"level":"warn","ts":1617279277.5422955,"caller":"plugin/hclog_adapter.go:69","msg":"error closing client during Kill","plugin_id":"com.cpanato.alertmanager","wrapped_extras":"errunexpected EOF"} {"level":"warn","ts":1617279277.5427206,"caller":"plugin/hclog_adapter.go:71","msg":"plugin failed to exit gracefully","plugin_id":"com.cpanato.alertmanager"} {"level":"error","ts":1617279277.5431993,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"SqlTeamStore.GetByName: Couldn't find an existing command., name=http://mt.lan:8065/team-dev,sql: no rows in result set"} {"level":"error","ts":1617279277.603872,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"SqlTeamStore.GetByName: Couldn't find an existing command., name=http://mt.lan:8065/team-dev,sql: no rows in result set"} {"level":"info","ts":1617279277.6219296,"caller":"bleveengine/bleve.go:267","msg":"UpdateConf Bleve"} {"level":"error","ts":1617279277.6514676,"caller":"mlog/log.go:190","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"SqlTeamStore.GetByName: Couldn't find an existing command., name=http://mt.lan:8065/team-dev,sql: no rows in result set"}
`

**Comment by cpanato** [comment]
hello, i tried with MM version 5.26.2 and works for me
![Screenshot 2021-04-27 at 13 30 34](https://user-images.githubusercontent.com/4115580/116234387-d0645c00-a75c-11eb-8173-483ee6302c44.png)
![Screenshot 2021-04-27 at 13 30 25](https://user-images.githubusercontent.com/4115580/116234391-d0fcf280-a75c-11eb-8b91-8e8e5a67a608.png)
![Screenshot 2021-04-27 at 13 29 09](https://user-images.githubusercontent.com/4115580/116234392-d1958900-a75c-11eb-8624-6e225fd68e8a.png)
![Screenshot 2021-04-27 at 13 29 01](https://user-images.githubusercontent.com/4115580/116234393-d22e1f80-a75c-11eb-9d9b-6d4115578d8f.png)

**Comment by edwelch** [comment]
**Problem solved** 

In **README.md** in step **4** "`For each, use the URL of the team or channel instead of their respective display names`".
For Team and Channel **use respective names instead URL's**. If you use URL's, Alertmanager plugin will not start.
