### ISSUE TITLE
Not Working with Mattermost 5.17

### ISSUE THREAD

**Issue by ltsavar** [cpanato/mattermost-plugin-alertmanager#3]
The Plugin is not working anymore with newer Versions of Mattermost.
Old Versions are having Problems see #2 
In Mattermost 5.17.3 it won't start. I tried setting the Team as URL and as name. Nothing worked.

The error message is:

{"level":"error","ts":1579856878.0848882,"caller":"mlog/log.go:174","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"unable to start plugin: com.cpanato.alertmanager: SqlTeamStore.GetByName: Unable to find the existing team, name=URL,sql: no rows in result set","errorVerbose":"SqlTeamStore.GetByName: Unable to find the existing team, name=URL,sql: no rows in result set\nunable to start plugin: com.cpanato.alertmanager\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/go/src/github.com/mattermost/mattermost-server/plugin/environment.go:251\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:100\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins.func2\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:183\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners.func1\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:35\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:333\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/mattermost/mattermost-server/config/common.go:90\ngithub.com/mattermost/mattermost-server/config.(*FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:107\ngithub.com/mattermost/mattermost-server/app.(*App).SaveConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:378\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:333\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/api4/plugin.go:298\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/web/handlers.go:148\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/NYTimes/gziphandler/gzip.go:336\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}
{"level":"error","ts":1579856878.1300879,"caller":"mlog/log.go:174","msg":"Unable to activate plugin","plugin_id":"jenkins","error":"unable to start plugin: jenkins: Please add Jenkins URL in plugin settings","errorVerbose":"Please add Jenkins URL in plugin settings\nunable to start plugin: jenkins\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/go/src/github.com/mattermost/mattermost-server/plugin/environment.go:251\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:100\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins.func2\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:183\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners.func1\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:35\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:333\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/mattermost/mattermost-server/config/common.go:90\ngithub.com/mattermost/mattermost-server/config.(*FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:107\ngithub.com/mattermost/mattermost-server/app.(*App).SaveConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:378\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:333\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/api4/plugin.go:298\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/web/handlers.go:148\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/NYTimes/gziphandler/gzip.go:336\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}

**Comment by cpanato** [comment]
@ltsavar  thanks for the report, i will try to find some time to fix that

**Comment by ltsavar** [comment]
I tried to compile it on my own with a newer mattermost-server version and the demo app from https://github.com/mattermost/mattermost-plugin-demo/ but it still failed with

/usr/bin/go vet ./...
# github.com/cpanato/mattermost-plugin-alertmanager/server [github.com/cpanato/mattermost-plugin-alertmanager/server.test]
server/webhook.go:23:14: undefined: notify.WebhookMessage
make: *** [Makefile:69: govet] Fehler 2

**Comment by cpanato** [comment]
same here you need to set an
![Screenshot 2020-01-24 at 15 28 07](https://user-images.githubusercontent.com/4115580/73076383-4cb72200-3ebe-11ea-993b-f6b82d589545.png)
 existing team name

**Comment by cpanato** [comment]
for example the team name you can get in the URL (in the screenshot marked in the red box) and team (blue)
![Screenshot 2020-01-24 at 15 30 56](https://user-images.githubusercontent.com/4115580/73076593-b33c4000-3ebe-11ea-9a3c-7d7750355837.png)

**Comment by cpanato** [comment]
Also tested with 5.17 and works

**Comment by ltsavar** [comment]
The release version from: https://github.com/cpanato/mattermost-plugin-alertmanager/releases/download/v0.0.1/com.cpanato.alertmanager-0.0.1.tar.gz
is not working for me. 

{"level":"error","ts":1579876719.0602252,"caller":"mlog/log.go:174","msg":"Unable to activate plugin","plugin_id":"com.cpanato.alertmanager","error":"unable to start plugin: com.cpanato.alertmanager: Channel.IsValid: Name must be 2 or more lowercase alphanumeric characters, id=75i5gjodp3bb5k5e5xndai67hr","errorVerbose":"Channel.IsValid: Name must be 2 or more lowercase alphanumeric characters, id=75i5gjodp3bb5k5e5xndai67hr\nunable to start plugin: com.cpanato.alertmanager\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/go/src/github.com/mattermost/mattermost-server/plugin/environment.go:251\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:100\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins.func2\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:183\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners.func1\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:35\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:333\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/mattermost/mattermost-server/config/common.go:90\ngithub.com/mattermost/mattermost-server/config.(*FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:107\ngithub.com/mattermost/mattermost-server/app.(*App).SaveConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:378\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:333\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/api4/plugin.go:298\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/web/handlers.go:148\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/NYTimes/gziphandler/gzip.go:336\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}

the team as just 2 Chars.

**Comment by cpanato** [comment]
@ltsavar is not complaining for the Team is failing in the Channel
``
Channel.IsValid: Name must be 2 or more lowercase alphanumeric characters
```

**Comment by ltsavar** [comment]
I did. Its correct. I tried an other one just in case. But still not working. 
Same error but both channel exists.

**Comment by cpanato** [comment]
@ltsavar can you send to me your config? otherwise it is very hard to help you, since I'm able to run the plugin using lastest master and version 5.17.0 as well

**Comment by ltsavar** [comment]
so the problem seems to be if i use just one Uppcase in the channel or in the team it brakes.
if i use lowercase everywhere its working. Maybe thats something we could quickfix somehow? :)

**Comment by cpanato** [comment]
I glad this is working.
all channels and team are lower case, the uppercase you see is the display name which can be any name.

closing this issue
