### ISSUE TITLE
Add it to the marketplace

### ISSUE THREAD

**Issue by rgarrigue** [cpanato/mattermost-plugin-alertmanager#5]
Hi there

Mind adding this one to mattermost plugin marketplace ? 

Best regards,

**Comment by dmpe** [comment]
Yes please!

**Comment by cpanato** [comment]
it is here: https://integrations.mattermost.com/?s=Prometheus%20AlertManager%20Plugin

**Comment by dmpe** [comment]
ohh, ok. sorry. 
can be closed from side

**Comment by rgarrigue** [comment]
Thanks
