### ISSUE TITLE
Support for Mattermost Cloud

### ISSUE THREAD

**Issue by Danpiel** [cpanato/mattermost-plugin-alertmanager#53]
Hello, is there a way to deploy this plugin in Mattermost Cloud instance or self-host independently and connect to the cloud ?

**Comment by cpanato** [comment]
i think this is a question to the mattermost team itself, i dont have access to the MMcloud

cc @hanzei

**Comment by hanzei** [comment]
Once the plugin is in the Marketplace, it can be installed on Mattermost Cloud. Please follow https://github.com/mattermost/mattermost-marketplace/issues/316 for updates.
