### ISSUE TITLE
why is the icon broken somewhen ? 

### ISSUE THREAD

**Issue by rgarrigue** [cpanato/mattermost-plugin-alertmanager#6]
Hi there

I specified an icon for the bot, which seems to be broken more often than not. Any idea why ? 

![image](https://user-images.githubusercontent.com/1872031/78527092-4b6a7580-77dc-11ea-91a5-c482b59e2d83.png)

![image](https://user-images.githubusercontent.com/1872031/78527115-5a512800-77dc-11ea-81f5-9407d0e61aa3.png)

Thanks for any help

**Comment by ltsavar** [comment]
Jup it is. But it was already fixed in #4

**Comment by cpanato** [comment]
thanks!
