### ISSUE TITLE
How can I customize the alert message ? 

### ISSUE THREAD

**Issue by rgarrigue** [cpanato/mattermost-plugin-alertmanager#8]
Hi

I'ld like to make those shorter

![image](https://user-images.githubusercontent.com/1872031/78527574-920c9f80-77dd-11ea-8e4f-736430b48095.png)

How can I edit the message template ?

Best regards,

**Comment by cpanato** [comment]
@rgarrigue This you can configure in the alertmanager side, the plugin just receives the messages
